### ISSUE TITLE
Request auction button -> JS error, UI doesn't update, but auction created

### ISSUE THREAD

**Issue by ianw-da** [digital-asset/daml-finance-app#38]
When creating a new auction (http://localhost:3000/#/distribution/new/auction) pressing the "Request Auction" button appears not to do anything.
JS console has the following error:
```
index.es5.js:88 Uncaught {kind: 'DecoderError', input: Array(6), at: 'input[0]', message: 'expected a value matching one of the decoders, got…79e95f7:Daml.Finance.Holding.Fungible:Fungible""]'}
withException @ index.es5.js:88
onWsMessage @ index.js:1403
index.es5.js:88 Uncaught {kind: 'DecoderError', input: Array(2), at: 'input[0]', message: 'expected a value matching one of the decoders, got…79e95f7:Daml.Finance.Holding.Fungible:Fungible""]'}
withException @ index.es5.js:88
onWsMessage @ index.js:1403
index.es5.js:88 Uncaught {kind: 'DecoderError', input: Array(2), at: 'input[0]', message: 'expected a value matching one of the decoders, got…79e95f7:Daml.Finance.Holding.Fungible:Fungible""]'}
withException @ index.es5.js:88
onWsMessage @ index.js:1403
index.es5.js:88 Uncaught {kind: 'DecoderError', input: Array(2), at: 'input[0]', message: 'expected a value matching one of the decoders, got…79e95f7:Daml.Finance.Holding.Fungible:Fungible""]'}
withException @ index.es5.js:88
onWsMessage @ index.js:1403
index.es5.js:88 Uncaught {kind: 'DecoderError', input: Array(2), at: 'input[0]', message: 'expected a value matching one of the decoders, got…79e95f7:Daml.Finance.Holding.Fungible:Fungible""]'}
withException @ index.es5.js:88
onWsMessage @ index.js:1403
index.js:253 Uncaught (in promise) Error: Failed to look up template 8e0e4f359d0f65be65883ff8bd047511f33b97b0ead9d6b47e10a681879e95f7:Daml.Finance.Holding.Account:Account. Make sure your @daml/types version agrees with the used Daml SDK version.
    at lookupTemplate (index.js:253:1)
    at index.js:328:1
    at index.es5.js:430:1
    at andThen (index.es5.js:135:1)
    at Decoder.decode (index.es5.js:429:1)
    at Decoder.decode (index.es5.js:517:1)
    at Decoder.decode (index.es5.js:746:1)
    at decodeValue_1 (index.es5.js:551:1)
    at index.es5.js:557:1
    at Array.reduce (<anonymous>)
```
However the auction is created and can be seen at http://localhost:3000/#/distribution/auctions

Tested on #37

**Comment by GeorgSchneider** [comment]
Fixed in https://github.com/digital-asset/daml-finance-app/pull/41
