### ISSUE TITLE
Close Auction now goes to "Auction not found" message

### ISSUE THREAD

**Issue by ianw-da** [digital-asset/daml-finance-app#39]
When an auction is closed (logged in as Agent), there used to be a summary page showing the bond allocations. Now we just get an "Auction not found" message centre page. However the auction is closed and the allocations appear to be correct. JS console:

```
index.es5.js:88 Uncaught 
{kind: 'DecoderError', input: Array(2), at: 'input[0]', message: 'expected a value matching one of the decoders, got…79e95f7:Daml.Finance.Holding.Fungible:Fungible""]'}
index.es5.js:88 Uncaught 
{kind: 'DecoderError', input: Array(2), at: 'input[0]', message: 'expected a value matching one of the decoders, got…79e95f7:Daml.Finance.Holding.Fungible:Fungible""]'}
index.es5.js:88 Uncaught 
{kind: 'DecoderError', input: Array(2), at: 'input[0]', message: 'expected a value matching one of the decoders, got…79e95f7:Daml.Finance.Holding.Fungible:Fungible""]'}
index.es5.js:88 Uncaught 
{kind: 'DecoderError', input: Array(2), at: 'input[0]', message: 'expected a value matching one of the decoders, got…79e95f7:Daml.Finance.Holding.Fungible:Fungible""]'}
index.es5.js:88 Uncaught 
{kind: 'DecoderError', input: Array(6), at: 'input[0]', message: 'expected a value matching one of the decoders, got…1879e95f7:Daml.Finance.Holding.Account:Account""]'}
index.js:253 Uncaught (in promise) Error: Failed to look up template 8e0e4f359d0f65be65883ff8bd047511f33b97b0ead9d6b47e10a681879e95f7:Daml.Finance.Holding.Account:Account. Make sure your @daml/types version agrees with the used Daml SDK version.
    at lookupTemplate (index.js:253:1)
    at index.js:328:1
    at index.es5.js:430:1
    at andThen (index.es5.js:135:1)
    at Decoder.decode (index.es5.js:429:1)
    at Decoder.decode (index.es5.js:517:1)
    at Decoder.decode (index.es5.js:746:1)
    at decodeValue_1 (index.es5.js:551:1)
    at index.es5.js:557:1
    at Array.reduce (<anonymous>)
```
This is on #37.

**Comment by GeorgSchneider** [comment]
Fixed as well in https://github.com/digital-asset/daml-finance-app/pull/41
